version: '3.8'

services:
  fsq_map:
    build: .
    container_name: fsq_map
    restart: always
    ports:
      - "5005:5005"
    env_file:
      - .env
    networks:
      - oci_bridge

networks:
  oci_bridge:
    external: true
