services:
  fsq_map:
    build: .
    container_name: fsq_map
    restart: always
    ports:
      - "5005:5005"
    env_file:
      - .env
    networks:
      oci_bridge:
        ipv4_address: 172.19.0.2

networks:
  oci_bridge:
    external: true
